version: "3.9"
services:
  db:
    platform: linux/amd64 # configuration for M1 macs
    image: mysql
    container_name: mysql_db
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: product_db